@startuml UserRegisterFlow
actor Cliente

Cliente -> AuthController : POST /auth/register\n(CreateUserDto)
AuthController -> AuthService : register(user)
AuthService -> RegisterUserUseCase : execute(user)
RegisterUserUseCase -> UserDomainService : validarDados(user)
RegisterUserUseCase -> UserEntity : criarInstancia(user)
RegisterUserUseCase -> UserRepository : save(UserEntity)
UserRepository --> RegisterUserUseCase : User criado
RegisterUserUseCase --> AuthService : CreateUserResponseDto
AuthService --> AuthController : CreateUserResponseDto
AuthController --> Cliente : HTTP 201 + dados do usuário

@enduml

' TODO - Confirmação de e-mail (Microservice de e-mail)